config/routes.rb
Rails.application.routes.draw do

  resources :sessions do
    collection do
      post "login"
      delete "logout"
    end
  end

  resources :users do
    get '/users/:id', to: 'users#show', as: 'user'
  end

  resources :accounts

  root 'sessions#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :user_type
  belongs_to :location_type
  has_many :messages
  has_many :reports
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  has_many :users
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		youve_got_mail()
		daily_dose_of_data()
		unless current_user
			redirect_to "/sessions"
		end
		if params[:uname]
			params[:id] = User.find_by_username(params[:uname]).id
			redirect_to user_path(params[:id])
		else
			@users = User.all
		end
	end

	

	def show
		daily_dose_of_data()
		@uname = User.find_by_id(params[:id]).username
		if !User.find_by_username(@uname)
			render "norecord"
		else
			@view_messages = []
			build_array()
			if !@view_messages.any?
				render "norecord"
			else
				@gospel = 0
				@converts = 0
				@baptisms = 0
				@church_plants = 0
				@view_messages.each do |view_message|
				case view_message.code_id.to_i
					when 101
						@gospel = @gospel + view_message.message_count.to_i
					when 201
						@converts = @converts + view_message.message_count.to_i
					when 301
						@baptisms = @baptisms + view_message.message_count.to_i
					when 401
						@church_plants = @church_plants + view_message.message_count.to_i
					end
				end
			end
		end
	end

	def build_array()
		@view_messages = []
		@start_time = Date.new(2015,02,07)
		@end_time = (Date.today + 2).to_s(:db)
		@user_id = User.find_by_username(@uname).id
		cmd = "SELECT * FROM view_users(\'#{@start_time}\', \'#{@end_time}\', #{@user_id})" 
		temp_results = ActiveRecord::Base.connection.exec_query(cmd)
		temp_results.each do |view_message_temp|
			view_message = ViewMessage.new( view_message_temp["code_id"],
											view_message_temp["message_id"],
											view_message_temp["message"],
											view_message_temp["message_count"],
											view_message_temp["username"],
											view_message_temp["usertype"],
											view_message_temp["user_id"],
											view_message_temp["location_name"],
											view_message_temp["code_type"],
											view_message_temp["code_action"],
											view_message_temp["message_created_at"],
											)
			
			@view_messages << view_message
		end
	end

end

app/views/users/_daily_footer.html.erb
<div class="well">
	<div class="row">
  		<div class="col-xs-12 col-md-12">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title" >
						Today's Activity
					</h3>
				</div>
				<ul class="list-inline panel-body">
					<li>Gospel Presentations: <%= @daily_gospel %></li>
			  		<li>Conversions: <%= @daily_converts %></li>
			  		<li>Baptisms: <%= @daily_baptisms %></li>
			  		<li>Churches Planted: <%= @daily_church_plants %></li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/users/_formtop.html.erb
<nav id="header" class="navbar navbar-default" role="navigation">
	<%= form_tag(users_path, :method => "get", :class => "navbar-left navbar-form", :name =>nil) do %>
		
		<a href="/users">
			<%= image_tag("logo.png") %>
		</a>

		<%= label_tag(:uname, "Username", :class => 'form-group') %>
		<%= text_field_tag(:uname, params[:uname]) %>
		<%= submit_tag("Fetch", :class => 'btn btn-default btn-info navbar-btn', :name => nil) %>
	<% end %>
	<%= link_to('Logout', logout_sessions_path, method: :delete, class: "btn btn-link navbar-right") %>
	<%= link_to('Create Account', accounts_path, class: "btn btn-link navbar-right") %>
	<%= link_to('Home', users_path, class: "btn btn-link navbar-right") %>
	


</nav>

app/views/users/index.html.erb
<div>
	<%= render partial: "formtop" %>
</div>

<div class="container-fluid">
  	<div class="row">
  		<div class="col-xs-6 col-md-4">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title" >
						All Users
					</h3>
				</div>
				<div class="panel-body">
					<% @users.each do |u| %>
						<%= link_to( user_path(u.id) ) do %>
							<p><%= u.username %></p>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

<div>
  <%= render partial: "daily_footer" %>
</div>

app/views/users/norecord.html.erb
<div>
	<%= render partial: "formtop" %>
</div>

<div class="panel panel-danger">
	<div class="panel-heading">
		<h3>No Records Found for <%= @uname %></h3>
	</div>
</div>

<div>
	<%= render partial: "daily_footer" %>
</div>

app/views/users/show.html.erb
<div>
	<%= render partial: "formtop" %>
</div>

<div class="container-fluid">
  	<div class="row">
  		<div class="col-xs-6 col-md-4">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title" >
						<%= @uname %>
					</h3>
				</div>
				<div class="panel-body">
					<p>Presented the gospel: <%= @gospel %></p>
			  		<p>Conversions: <%= @converts %></p>
			  		<p>Performed baptisms: <%= @baptisms %></p>
			  		<p>Planted churches: <%= @church_plants %></p>
				</div>
			</div>
		</div>
	</div>
</div>

<div>
	<%= render partial: "daily_footer" %>
</div>